[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trinity_solana = "8tsvXCJwKZhNwe3U2MVWdP1n4EkgDVAq4sQCM4Ry2XqS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "https://api.devnet.solana.com"
wallet = "/Users/jamiebell/.config/solana/devnet.json"

# wallet = "~/.config/solana/id.json"

[scripts]
build-client = "anchor client-gen target/idl/trinity_solana.json --typescript-dir ./target/types"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
